load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "apdl",
    srcs = [
        "src/deck_writer.cc",
    ],
    hdrs = [
        "include/apdl/apdl_entity.hh",
        "include/apdl/deck_writer.hh",
        "include/apdl/keypoint.hh",
        "include/apdl/material.hh",
        "include/apdl/model.hh",
        "include/apdl/node.hh",
        "include/apdl/section.hh",
        "include/apdl/shell181.hh",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@fmt",
        "@spdlog//:spdlog",
    ],
)
