load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "core",
    srcs = ["src/parser.cc", "src/core.cc"],
    hdrs = ["include/core/parser.h", "include/core/core.h"],
    includes = ["include"],
    deps = [
        "//src/common",
        "//src/logtools",
        "//src/lsdyna",
        "@spdlog//:spdlog",
        "@fmt",
        "@gflags"
    ],
)

cc_binary(
    name = "lsdynatoapdl",
    srcs = ["src/main.cc"],
    deps = [
        ":core",
        "@fmt",
        "@spdlog",
        "@gflags"
    ],
)
